### ISSUE TITLE
TimeoutError: Navigation timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by w4rgrum** [grafana/grafana-image-renderer#169]
**What happened**

On a dashboard that is slow to load, the image renderer threw this error:

TimeoutError: Navigation timeout of 30000 ms exceeded
    at /usr/src/app/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21
  -- ASYNC --
    at Frame.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/usr/src/app/node_modules/puppeteer/lib/Page.js:675:49)
    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:112:23)
    at Browser.<anonymous> (/usr/src/app/build/browser/browser.js:170:24)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/build/browser/browser.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

This timeout does not match the one provided in input of the query to the renderer, thus we have no mean to render this slow dashboard (except trying to fasten it).

**What you expected to happen**

Timeout occurs after the timeout parameter provided to the renderer is matched.

**Anything else we need to know?**

A possible fix would be to set the puppeteer timeout value to a value consistent with the timeout parameter of the query.
Thus either disabling the puppeteer timeout (setting it to 0) or using the timeout opt + some seconds.

https://github.com/grafana/grafana-image-renderer/blob/f5f2192af9609a45f93d2822160548c2c7c5c4c0/src/browser/browser.ts#L178

```typescript
await page.goto(options.url, { waitUntil: 'networkidle0', timeout: 0 });
```

**Environment:**

* Grafana Image Renderer version: 2.0.0
* Grafana version: 7.1.1

**Comment by kazeborja** [comment]
This will be something amazing to move forward, since currently is the only reason why we are packaging the plugin on our own :) 

About the PR linked I have the feeling it's missing a rebase.

**Comment by idl0r** [comment]
Same problem. Also 2.0.0, grafana 7.3.6
