### ISSUE TITLE
Failing render because of timeout

### ISSUE THREAD

**Issue by FUSAKLA** [grafana/grafana-image-renderer#25]
Hi, I deployed the renderer as a stand alone server and tried rendering single panel which loads almost instantly but it times out in the renderer. 

Not sure what causes this timeout and how I can resolve this? Can I configure it somewhere?

```
{ TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (/usr/src/app/node_modules/puppeteer/lib/NavigatorWatcher.js:74:21)
  stack:
   'TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded\n    at Promise.then (/usr/src/app/node_modules/puppeteer/lib/NavigatorWatcher.js:74:21)',
  message: 'Navigation Timeout Exceeded: 30000ms exceeded',
  name: 'TimeoutError',
  isBoom: true,
  isServer: true,
  data: null,
  output:
   { statusCode: 500,
     payload:
      { statusCode: 500,
        error: 'Internal Server Error',
        message: 'An internal server error occurred' },
     headers: {} },
  reformat: [Function],
  isDeveloperError: true }

```

Thanks for any info.

**Comment by FUSAKLA** [comment]
Hmpf.. I see the server calls the url of the referrer and it is not accessible internally.

I found the `callback_url` setting in defaults.ini of grafana

https://github.com/grafana/grafana/blob/e5e7bd315357d7b6ea016e1098a1acbdc3b35d66/conf/defaults.ini#L664

Is this possible to override the url which will the renderer call or is there any other way?

**Comment by FUSAKLA** [comment]
Ok, I found out it is exactly that setting. Unfortunately in my case certificates does not match after the callback url change :/ Might be usefull to document the `callback_url` in the readme of this repo. 

Sorry for the false alarm.
