### ISSUE TITLE
Image renderer return empty image of Geomap panel

### ISSUE THREAD

**Issue by trashrapov** [grafana/grafana-image-renderer#316]
**What happened**:
Image renderer returns empty image of Geomap panel. While in grafana  Geomap panel is displayed correctly.
Other types of panels(Graph, etc...) are rendered correctly. 

Image returned by renderer:
![image](https://user-images.githubusercontent.com/49598671/149299290-dc206050-15e2-440d-91c9-be8f8a7921ea.png)

Image in grafana:
![image](https://user-images.githubusercontent.com/49598671/149300192-8be2ba9a-bbfe-4c0f-9c8b-b42495ae2e49.png)

**What you expected to happen**:
Correctly rendered image of Geomap panel.

**How to reproduce it (as minimally and precisely as possible)**:
I start grafana and renderer by docker-compose:
```
version: '2.0'

volumes:
    grafana_data: {}

networks:
#  front-tier:
  back-tier:

services:
  grafana:
    image: grafana/grafana:8.1.8
    user: "472"
    ports:
      - 3300:3000
    environment:
        GF_RENDERING_SERVER_URL: http://renderer:8081/render
        GF_RENDERING_CALLBACK_URL: http://grafana:3000/
        GF_LOG_FILTERS: rendering:debug
    volumes:
      - ./grafana/certs/:/certs
      - ./grafana/provisioning/:/etc/grafana/provisioning
      - /STORAGE/SSD-1TB/grafana.test_data:/var/lib/grafana
    env_file:
      - ./grafana/config.monitoring
    networks:
      - back-tier
    restart: always
  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081
    networks:
      - back-tier
    environment:
      RENDERING_VERBOSE_LOGGING: 'true'
      LOG_LEVEL: debug
```

**Anything else we need to know?**:
Log of renderer when rendering empty Geomap image:
```
{"level":"debug","message":"Render request received","url":"http://grafana:3000/d-solo/d_ucLI1nz/maps?orgId=1&from=1642061384298&to=1642063184298&panelId=2&width=1000&height=500&tz=Europe%2FMoscow&render=1"}
{"deviceScaleFactor":"1","height":"500","level":"debug","message":"Setting viewport for page","width":"1000"}
{"domain":"grafana","level":"debug","message":"Setting cookie for page","renderKey":"DmgIxLDFH1l1DoAimv0IxJLziaLWCcP0"}
{"level":"debug","message":"Moving mouse on page","x":1000,"y":500}
{"level":"debug","message":"Navigating and waiting for all network requests to finish","url":"http://grafana:3000/d-solo/d_ucLI1nz/maps?orgId=1&from=1642061384298&to=1642063184298&panelId=2&width=1000&height=500&tz=Europe%2FMoscow&render=1"}
{"level":"debug","message":"Browser request","method":"GET","url":"http://grafana:3000/d-solo/d_ucLI1nz/maps?orgId=1&from=1642061384298&to=1642063184298&panelId=2&width=1000&height=500&tz=Europe%2FMoscow&render=1"}
{"level":"debug","message":"Browser request","method":"GET","url":"http://grafana:3000/public/fonts/roboto/RxZJdnzeo3R5zSexge8UUVtXRa8TVwTICgirnJhmVJw.woff2"}
{"level":"debug","message":"Browser request finished","method":"GET","url":"http://grafana:3000/d-solo/d_ucLI1nz/maps?orgId=1&from=1642061384298&to=1642063184298&panelId=2&width=1000&height=500&tz=Europe%2FMoscow&render=1"}
{"level":"debug","message":"Browser request","method":"GET","url":"http://grafana:3000/public/build/grafana.dark.8037849dbb02d3339929.css"}
{"level":"debug","message":"Browser request","method":"GET","url":"http://grafana:3000/public/build/runtime.8037849dbb02d3339929.js"}
{"level":"debug","message":"Browser request","method":"GET","url":"http://grafana:3000/public/build/angular~app.8037849dbb02d3339929.js"}
{"level":"debug","message":"Browser request","method":"GET","url":"http://grafana:3000/public/build/app.8037849dbb02d3339929.js"}
{"level":"debug","message":"Browser request","method":"GET","url":"http://grafana:3000/public/build/moment~app.8037849dbb02d3339929.js"}
{"level":"debug","message":"Browser request","method":"GET","url":"http://grafana:3000/public/build/vendors~app.8037849dbb02d3339929.js"}
{"level":"debug","message":"Browser request finished","method":"GET","url":"http://grafana:3000/public/fonts/roboto/RxZJdnzeo3R5zSexge8UUVtXRa8TVwTICgirnJhmVJw.woff2"}
{"level":"debug","message":"Browser request finished","method":"GET","url":"http://grafana:3000/public/build/runtime.8037849dbb02d3339929.js"}
{"level":"debug","message":"Browser request finished","method":"GET","url":"http://grafana:3000/public/build/grafana.dark.8037849dbb02d3339929.css"}
{"level":"debug","message":"Browser request finished","method":"GET","url":"http://grafana:3000/public/build/moment~app.8037849dbb02d3339929.js"}
{"level":"debug","message":"Browser request finished","method":"GET","url":"http://grafana:3000/public/build/angular~app.8037849dbb02d3339929.js"}
{"level":"debug","message":"Browser request","method":"GET","url":"http://grafana:3000/public/img/grafana_icon.svg"}
{"level":"debug","message":"Browser request","method":"GET","url":"http://grafana:3000/public/fonts/roboto/CWB0XYA8bzo0kSThX0UTuA.woff2"}
{"level":"debug","message":"Browser request finished","method":"GET","url":"http://grafana:3000/public/img/grafana_icon.svg"}
{"level":"debug","message":"Browser request finished","method":"GET","url":"http://grafana:3000/public/fonts/roboto/CWB0XYA8bzo0kSThX0UTuA.woff2"}
{"level":"debug","message":"Browser request finished","method":"GET","url":"http://grafana:3000/public/build/app.8037849dbb02d3339929.js"}
{"level":"debug","message":"Browser request finished","method":"GET","url":"http://grafana:3000/public/build/vendors~app.8037849dbb02d3339929.js"}
{"column":1985631,"level":"debug","line":1,"message":"Browser console debug","msg":"centrifuge config JSHandle@object","url":"http://grafana:3000/public/build/vendors~app.8037849dbb02d3339929.js"}
{"column":1985631,"level":"debug","line":1,"message":"Browser console debug","msg":"client will connect to websocket endpoint","url":"http://grafana:3000/public/build/vendors~app.8037849dbb02d3339929.js"}
{"column":1985631,"level":"debug","line":1,"message":"Browser console debug","msg":"start connecting","url":"http://grafana:3000/public/build/vendors~app.8037849dbb02d3339929.js"}
{"column":1985631,"level":"debug","line":1,"message":"Browser console debug","msg":"Status disconnected -> connecting","url":"http://grafana:3000/public/build/vendors~app.8037849dbb02d3339929.js"}
{"level":"debug","message":"Browser request","method":"GET","url":"http://grafana:3000/public/build/default~DashboardPage~SoloPanelPage.8037849dbb02d3339929.js"}
{"level":"debug","message":"Browser request","method":"GET","url":"http://grafana:3000/public/build/SoloPanelPage.8037849dbb02d3339929.js"}
{"level":"debug","message":"Browser request finished","method":"GET","url":"http://grafana:3000/public/build/default~DashboardPage~SoloPanelPage.8037849dbb02d3339929.js"}
{"column":1985631,"level":"debug","line":1,"message":"Browser console debug","msg":"reset retries count to 0","url":"http://grafana:3000/public/build/vendors~app.8037849dbb02d3339929.js"}
{"column":1985631,"level":"debug","line":1,"message":"Browser console debug","msg":"Status connecting -> connected","url":"http://grafana:3000/public/build/vendors~app.8037849dbb02d3339929.js"}
{"column":1985631,"level":"debug","line":1,"message":"Browser console debug","msg":"no private channels found, no need to make request","url":"http://grafana:3000/public/build/vendors~app.8037849dbb02d3339929.js"}
{"level":"debug","message":"Browser request finished","method":"GET","url":"http://grafana:3000/public/build/SoloPanelPage.8037849dbb02d3339929.js"}
{"level":"debug","message":"Browser request","method":"GET","url":"http://grafana:3000/api/dashboards/uid/d_ucLI1nz"}
{"level":"debug","message":"Browser request finished","method":"GET","url":"http://grafana:3000/api/dashboards/uid/d_ucLI1nz"}
{"level":"debug","message":"Browser request","method":"GET","url":"http://grafana:3000/public/build/default~lokiPlugin~prometheusPlugin.8037849dbb02d3339929.js"}
{"level":"debug","message":"Browser request","method":"GET","url":"http://grafana:3000/public/build/prometheusPlugin.8037849dbb02d3339929.js"}
{"level":"debug","message":"Browser request finished","method":"GET","url":"http://grafana:3000/public/build/default~lokiPlugin~prometheusPlugin.8037849dbb02d3339929.js"}
{"level":"debug","message":"Browser request finished","method":"GET","url":"http://grafana:3000/public/build/prometheusPlugin.8037849dbb02d3339929.js"}
{"level":"debug","message":"Browser request","method":"POST","url":"http://grafana:3000/api/datasources/proxy/1/api/v1/series"}
{"level":"debug","message":"Browser request finished","method":"POST","url":"http://grafana:3000/api/datasources/proxy/1/api/v1/series"}
{"level":"debug","message":"Browser request","method":"POST","url":"http://grafana:3000/api/datasources/proxy/1/api/v1/series"}
{"level":"debug","message":"Browser request finished","method":"POST","url":"http://grafana:3000/api/datasources/proxy/1/api/v1/series"}
{"level":"debug","message":"Browser request","method":"GET","url":"http://grafana:3000/public/build/grafanaPlugin.8037849dbb02d3339929.js"}
{"level":"debug","message":"Browser request","method":"GET","url":"http://grafana:3000/public/build/default~geomapPanel.8037849dbb02d3339929.js"}
{"column":1985631,"level":"debug","line":1,"message":"Browser console debug","msg":"subscribing on 1/grafana/dashboard/uid/d_ucLI1nz","url":"http://grafana:3000/public/build/vendors~app.8037849dbb02d3339929.js"}
{"level":"debug","message":"Browser request","method":"GET","url":"http://grafana:3000/public/build/geomapPanel.8037849dbb02d3339929.js"}
{"level":"debug","message":"Browser request finished","method":"GET","url":"http://grafana:3000/public/build/grafanaPlugin.8037849dbb02d3339929.js"}
{"level":"debug","message":"Browser request finished","method":"GET","url":"http://grafana:3000/public/build/geomapPanel.8037849dbb02d3339929.js"}
{"level":"debug","message":"Browser request","method":"GET","url":"http://grafana:3000/api/annotations?from=1642061384298&to=1642063184298&limit=100&matchAny=false&dashboardId=3"}
{"level":"debug","message":"Browser request finished","method":"GET","url":"http://grafana:3000/api/annotations?from=1642061384298&to=1642063184298&limit=100&matchAny=false&dashboardId=3"}
{"level":"debug","message":"Browser request finished","method":"GET","url":"http://grafana:3000/public/build/default~geomapPanel.8037849dbb02d3339929.js"}
{"level":"debug","message":"Browser request","method":"POST","url":"http://grafana:3000/api/datasources/proxy/1/api/v1/query_range"}
{"level":"debug","message":"Browser request finished","method":"POST","url":"http://grafana:3000/api/datasources/proxy/1/api/v1/query_range"}
{"error":"Error: TypeError: Cannot read properties of undefined (reading 'indexOf')\n    at o (http://grafana:3000/public/build/default~geomapPanel.8037849dbb02d3339929.js:106:241782)\n    at new e (http://grafana:3000/public/build/default~geomapPanel.8037849dbb02d3339929.js:34:10952)\n    at e [as constructor] (http://grafana:3000/public/build/default~geomapPanel.8037849dbb02d3339929.js:34:18767)\n    at new e (http://grafana:3000/public/build/default~geomapPanel.8037849dbb02d3339929.js:34:22835)\n    at e.createRenderer (http://grafana:3000/public/build/default~geomapPanel.8037849dbb02d3339929.js:34:31765)\n    at e.getRenderer (http://grafana:3000/public/build/default~geomapPanel.8037849dbb02d3339929.js:106:28505)\n    at e.render (http://grafana:3000/public/build/default~geomapPanel.8037849dbb02d3339929.js:106:27800)\n    at e.renderFrame (http://grafana:3000/public/build/default~geomapPanel.8037849dbb02d3339929.js:106:175404)\n    at e.renderFrame_ (http://grafana:3000/public/build/default~geomapPanel.8037849dbb02d3339929.js:106:202167)\n    at e.<anonymous> (http://grafana:3000/public/build/default~geomapPanel.8037849dbb02d3339929.js:106:189566)","level":"error","message":"Browser uncaught exception"}
{"level":"debug","message":"Waiting for dashboard/panel to load","timeout":"60s"}
{"filePath":"/tmp/bdfac638.png","level":"debug","message":"Taking screenshot"}
{"error":"Error: TypeError: Cannot read properties of undefined (reading 'indexOf')\n    at o (http://grafana:3000/public/build/default~geomapPanel.8037849dbb02d3339929.js:106:241782)\n    at new e (http://grafana:3000/public/build/default~geomapPanel.8037849dbb02d3339929.js:34:10952)\n    at e [as constructor] (http://grafana:3000/public/build/default~geomapPanel.8037849dbb02d3339929.js:34:18767)\n    at new e (http://grafana:3000/public/build/default~geomapPanel.8037849dbb02d3339929.js:34:22835)\n    at e.createRenderer (http://grafana:3000/public/build/default~geomapPanel.8037849dbb02d3339929.js:34:31765)\n    at e.getRenderer (http://grafana:3000/public/build/default~geomapPanel.8037849dbb02d3339929.js:106:28505)\n    at e.render (http://grafana:3000/public/build/default~geomapPanel.8037849dbb02d3339929.js:106:27800)\n    at e.renderFrame (http://grafana:3000/public/build/default~geomapPanel.8037849dbb02d3339929.js:106:175404)\n    at e.renderFrame_ (http://grafana:3000/public/build/default~geomapPanel.8037849dbb02d3339929.js:106:202167)\n    at e.<anonymous> (http://grafana:3000/public/build/default~geomapPanel.8037849dbb02d3339929.js:106:189566)","level":"error","message":"Browser uncaught exception"}
{"file":"/tmp/bdfac638.png","level":"debug","message":"Deleting temporary file"}
{"level":"debug","message":"::ffff:192.168.96.2 - - [13/Jan/2022:09:16:18 +0000] \"GET /render?deviceScaleFactor=1.000000&domain=grafana&encoding=&height=500&renderKey=DmgIxLDFH1l1DoAimv0IxJLziaLWCcP0&timeout=60&timezone=Europe%2FMoscow&url=http%3A%2F%2Fgrafana%3A3000%2Fd-solo%2Fd_ucLI1nz%2Fmaps%3ForgId%3D1%26from%3D1642061384298%26to%3D1642063184298%26panelId%3D2%26width%3D1000%26height%3D500%26tz%3DEurope%252FMoscow%26render%3D1&width=1000 HTTP/1.1\" 200 5816 \"-\" \"Grafana/8.1.8\"\n"}
{"level":"debug","message":"Connection closed","url":"http://grafana:3000/d-solo/d_ucLI1nz/maps?orgId=1&from=1642061384298&to=1642063184298&panelId=2&width=1000&height=500&tz=Europe%2FMoscow&render=1"}
```

**Environment**:
- Grafana Image Renderer version: 3.3.0 latest
- Grafana version: 8.1.8
- Installed plugin or remote renderer service:
- OS Grafana Image Renderer is installed on:
- User OS & Browser:
- Others:

**Comment by zickzackhd** [comment]
I got the Same Issue.
## Renderd Image:
<img src="https://i.imgur.com/I2eYHEU.png"></img>
## Expected Image:
<img src="https://i.imgur.com/4aaf4U8.png"></img>
## Grafana World Map Configuration
<img src="https://user-images.githubusercontent.com/34350217/198849899-1c29ea26-6323-48c4-8fef-8c04a6722397.png"></img>

```yml
   grafana:
        image: grafana/grafana-oss
        restart: unless-stopped
        environment:
          GF_RENDERING_SERVER_URL: http://renderer:8081/render
          GF_RENDERING_CALLBACK_URL: http://grafana:3000/
        # GF_LOG_FILTERS: rendering:debug
#----------------------------------------------------------------
   renderer:
        image: grafana/grafana-image-renderer:latest
```
PS: All other Rendering stuff works well.

**Comment by kaffarell** [comment]
Happens to me too, looks like an bug in the renderer.

**Comment by kaffarell** [comment]
Can confirm this issue only happens when the Heatmap style is used. The default 'Marker' style works.

**Comment by hamzaalmali** [comment]
I have the same problem: I take screenshots of all existing maps, but when I convert it to a heat map, the screenshot appears blank.

**Comment by macabu** [comment]
There were a decent amount of changes related to Geomap panels within the past 2 years, so I encourage you to try again using a recent Grafana version.

I'll close this but feel free to reply here or open a new issue in case it doesnt work for you.
