### ISSUE TITLE
Error: net::ERR_BLOCKED_BY_ADMINISTRATOR

### ISSUE THREAD

**Issue by mzac** [grafana/grafana-image-renderer#343]
**What happened**:
When trying to use the new grafana-image-renderer plugin I get the following error:

```
logger=plugin.grafana-image-renderer t=2022-04-05T11:38:22.25-0400 lvl=eror msg="Error while trying to prepare page for screenshot" 
 url="http://localhost:3000/d-solo/0AtjC6s7z/test-alerts?orgId=1&panelId=2&render=1"
 err="Error: net::ERR_BLOCKED_BY_ADMINISTRATOR 
 at http://localhost:3000/d-solo/0AtjC6s7z/test-alerts?orgId=1&panelId=2&render=1\n    
 at navigate (/snapshot/grafana-image-renderer/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:156:23)\n    
 at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    
 at async FrameManager.navigateFrame (/snapshot/grafana-image-renderer/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:131:21)\n    
 at async Frame.goto (/snapshot/grafana-image-renderer/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:512:16)\n    
 at async Page.goto (/snapshot/grafana-image-renderer/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:16)\n   
 at async Browser.takeScreenshot (/snapshot/grafana-image-renderer/build/browser/browser.js:256:13)\n    
 at async Browser.render (/snapshot/grafana-image-renderer/build/browser/browser.js:230:20)\n   
 at async PluginGRPCServer.render (/snapshot/grafana-image-renderer/build/plugin/v2/grpc_plugin.js:95:13)"
```

**What you expected to happen**:
It should work

**How to reproduce it (as minimally and precisely as possible)**:
All my alerts give this error

**Anything else we need to know?**:
It was working in the past, not sure what changed.

**Environment**:
- Grafana Image Renderer version: 3.4.2
- Grafana version: 8.4.3
- Installed plugin or remote renderer service: plugin
- OS Grafana Image Renderer is installed on:  Red Hat Enterprise Linux Server release 7.9 (Maipo)
- User OS & Browser: n/a
- Others: n/a

**Comment by AgnesToulet** [comment]
Closing this issue as it's been a few months without any more information. Please reach out if you are still experience this issue with latest versions of Grafana and the image renderer.
