### ISSUE TITLE
grafana-image-renderer Request failed

### ISSUE THREAD

**Issue by LotusYTing** [grafana/grafana-image-renderer#423]
Devlools listening on ws://127.0.0.1:34499/devtools/browser/ af81592-4a35-423-bb75-d8cb75f0760d
[0506/021143.638314:WARNING:bluez abus manager. cc (248)] Floss manager not present, cannot set Floss enable/disable.
[0506/021143.645888:ERROR: angle_ platform_impl.cc (44)] RendererVk.cp:121 (VerifyExtensionsPresent) :
Extension not supported: VK KHR Surface
0505/021193.545957:ERROR:ang1e_DLatIozI_ 1mp1.cc (29)1 RenaezezVk.cpp:121 (VeziEyExEenGLonSPzeseAE) : ExEenSiom MoE eupozscea: v KriR xob_ SuzEace
[0506/021143.646009:ERROR:angle_platform_impl.cc (44) | Display.cp: 944 (initialize) : ANGLE Display: einitialize error 0: Internal Vulkan error (-7) : A requeste d extension is not supported, in ../../third party/angle/3rc/libANGLE/renderer /vulkan/RendererVk.cp, initialize: 1303.
[0506/021143.646066:ERROR:gl surface egl.cc (808)] EGL Driver message (Critical) eglinitialize: Internal Vulkan errOr (-1) : A requested extension is not suppo rted, in /../third party/angle/src/libANGLE/renderer/vulkan/RendererVk.cpp,initialize:1303.
(0506/021143.646112:ERROR:gI_surface_egl.cc (1430)) eglInitialize SWANGLE failed with errOr EGL_NOI_INITIALIZED
[0506/021143.646149:ERROR:gl ozone egl.cc (20) I GLSurfaceEGL:: InitializeOneoff failed.
[0506/021143.648487;ERROR: ViZ main impl.cc (188)) Exiting GPU process due to errors during initialization 10506/021143.664019:ERROR:gpu init. cc (440)] Passthrough is not supported,
GL is disabled, ANGLE is
("level"; "error", "message": "Request failed", "stack": "Error: Request aborted\n
at onaborted (/usz/ src/ app/node modules/ express/ 1ib/zesponse . j8:1030:15)1
at Array.onfinish (/usr/src/app/node modules/express/lib/response.js: 1066:50) \n at listener /usr/SIC/app/node modules/morgan/node_modules/on-finished/i ndex.§s:169:15) \n at onfinish Wusr/sIC/app/node modules /morgan/node modules/on-finished/index. js:100:5) In
at callback (/usz/ src/app/node modules/ee-fi
rst/index.js:55:10) \n at Socket.onevent (/usr/src/app/node modules/ee-first/index. js: 93:5) \n at Socket.emit (events.js:412:35) \n
at emitErrorNT (int
ernal/streams/destroy.js:106:8) \n at emitErrorCloseNT (internal/streams/destroy.js:74:3) \n
at processTicksAndRejections (internal/process/ task queues .j
3:82:21)
{"1evel" :debug", "message": "connection closed"}
TypeError: Cannot read property 'statusCode of undefined at /usr/src/app/build/service/http-server.js:135:42 at Layer.handle_error (/Ust/src/app/node_modules/express/lib/router/layer.js:71:5)
at trim prerix T/usI/ sIC/ app/node modules/express/1ib/ router/index. js:321:13)
at /usr/src/app/node modules /express/lib/router/index. js: 284:7
I
at Punction.proce3s paramg (/usr/ src/app/node modules/express/1ib/ router/ index. j3:341:12)
at next (/ust/3rc/app/node modules/express/lib/router/index. js: 275:10) at next (/usr/src/app/node modules/express/lib/router/route. js:127:14)
at /usr/src/app/build/service/http-server.js:44:21
at /usr/src/app/node modules/express/lib/response.js: 439:22
at onaborted (/usr/src/app/node_ modules/express/ 1ib/response . js:1032:5)

```
renderer:
image: grafana/grafana-image-renderer: 3.4.2 ports:
- "8081”
environment:
ENABLE METRICS: "true"
RENDERING DUMPIO: "true"
LOG LEVEL: debug
RENDERING ARGS: --no-sandbox,--disable-gpu
```

```[tasklist]
### Tasks
```

**Comment by Clarity-89** [comment]
From the stack trace it doesn't look like the issue here is with the image renderer. More likely the issue is with the GPU drivers being not up to date or Vulkan configuration issues.
