### ISSUE TITLE
Plugin v3.8.0 does not load: "Could not find Chrome (ver. 116.0.5845.96)" from puppeteer

### ISSUE THREAD

**Issue by chennin** [grafana/grafana-image-renderer#449]
**What happened**:

Image renderer plugin version 3.8.0 does not load, giving logs:

```
logger=plugin.grafana-image-renderer t=2023-08-25T21:15:31.654884325Z level=debug msg="Error: Could not find Chrome (ver. 116.0.5845.96). This can occur if either"
logger=plugin.grafana-image-renderer t=2023-08-25T21:15:31.654903285Z level=debug msg=" 1. you did not perform an installation before running the script (e.g. `npm install`) or"
logger=plugin.grafana-image-renderer t=2023-08-25T21:15:31.654910725Z level=debug msg=" 2. your cache path is incorrectly configured (which is: /usr/share/grafana/.cache/puppeteer)."
logger=plugin.grafana-image-renderer t=2023-08-25T21:15:31.654914485Z level=debug msg="For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration."
logger=plugin.grafana-image-renderer t=2023-08-25T21:15:31.654917835Z level=debug msg="    at ChromeLauncher.resolveExecutablePath (/snapshot/src/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:300:27)"
logger=plugin.grafana-image-renderer t=2023-08-25T21:15:31.654922826Z level=debug msg="    at ChromeLauncher.executablePath (/snapshot/src/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:180:25)"
logger=plugin.grafana-image-renderer t=2023-08-25T21:15:31.654926176Z level=debug msg="    at PuppeteerNode.executablePath (/snapshot/src/node_modules/puppeteer-core/lib/cjs/puppeteer/node/PuppeteerNode.js:170:31)"
logger=plugin.grafana-image-renderer t=2023-08-25T21:15:31.654929406Z level=debug msg="    at main (/snapshot/src/build/app.js:24:46)"
logger=plugin.grafana-image-renderer t=2023-08-25T21:15:31.654932416Z level=debug msg="    at Object.<anonymous> (/snapshot/src/build/app.js:75:1)"
logger=plugin.grafana-image-renderer t=2023-08-25T21:15:31.654935376Z level=debug msg="    at Module._compile (pkg/prelude/bootstrap.js:1926:22)"
logger=plugin.grafana-image-renderer t=2023-08-25T21:15:31.654938246Z level=debug msg="    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)"
logger=plugin.grafana-image-renderer t=2023-08-25T21:15:31.654941006Z level=debug msg="    at Module.load (node:internal/modules/cjs/loader:981:32)"
logger=plugin.grafana-image-renderer t=2023-08-25T21:15:31.654943776Z level=debug msg="    at Function.Module._load (node:internal/modules/cjs/loader:822:12)"
logger=plugin.grafana-image-renderer t=2023-08-25T21:15:31.654948296Z level=debug msg="    at Function.runMain (pkg/prelude/bootstrap.js:1979:12)"
logger=plugin.grafana-image-renderer t=2023-08-25T21:15:31.660405449Z level=error msg="plugin process exited" path=/var/lib/grafana-plugins/grafana-image-renderer/plugin_start_linux_amd64 pid=27 error="exit status 1"
```
And, the usual:
```
logger=modules t=2023-08-25T21:15:31.674892305Z level=info msg="module stopped" module=http-server
Error: ✗ *rendering.RenderingService run error: Unrecognized remote plugin message:
This usually means
  the plugin was not compiled for this architecture,
  the plugin is missing dynamic-link libraries necessary to run,
  the plugin is not executable by this process due to file permissions, or
  the plugin failed to negotiate the initial go-plugin protocol handshake

Additional notes about plugin:
  Path: /var/lib/grafana-plugins/grafana-image-renderer/plugin_start_linux_amd64
  Mode: -rwxr-xr-x
  Owner: 472 [grafana] (current: 472 [grafana])
  Group: 0 [root] (current: 0 [root])
  ELF architecture: EM_X86_64 (current architecture: amd64)
```

[log.txt](https://github.com/grafana/grafana-image-renderer/files/12443580/log.txt)

**How to reproduce it (as minimally and precisely as possible)**:

Build the official(?) [Grafana-with-Image-Renderer Dockerfile](https://github.com/grafana/grafana/blob/main/packaging/docker/custom/Dockerfile), then run the docker image.

```bash
mkdir -p /tmp/work && cd /tmp/work && \
wget https://raw.githubusercontent.com/grafana/grafana/main/packaging/docker/custom/Dockerfile && \
docker build --build-arg GF_INSTALL_IMAGE_RENDERER_PLUGIN=true -t grafana-plugin-test . < ./Dockerfile && \
docker run --rm -e GF_LOG_LEVEL="debug" grafana-plugin-test | tee log.txt
```

**Anything else we need to know?**:

3.7.2 works.

Directly using the official images `grafana/grafana` or `grafana/grafana:latest-ubuntu`, and passing `-e GF_INSTALL_PLUGINS="grafana-image-renderer"`, also does not work. 3.8.0 still does not load; 3.7.2 does load (but would not actually work on those images due to missing dependencies). 

Setting `GF_PLUGIN_RENDERING_CHROME_BIN` does not fix it.

If I use `strace` and try to run 3.8.0 directly, I can see an error on a path that doesn't exist just before the error message is printed. No folders named `puppeteer` exist in the container.  3.7.2 more correctly tells me not to run a plugin directly.

```
148   pread64(17, "syntax = \"proto3\";\n\npackage grpc.health.v1;\n\nmessage HealthCheckRequest {\n  string service = 1;\n}\n\nmessage HealthCheckResponse {\n  enum ServingStatus {\n    UNKNOWN = 0;\n    SERVING = 1;\n    NOT_SERVING = 2;\n  }\n  ServingStatus status = 1;\n}\n\nservice Health"..., 323, 42591608) = 323
148   mprotect(0x7f73ce903000, 245760, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
148   mprotect(0x7f73ce903000, 245760, PROT_READ|PROT_EXEC) = 0
148   mprotect(0x7f73ce903000, 245760, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
148   mprotect(0x7f73ce903000, 245760, PROT_READ|PROT_EXEC) = 0

148   access("/home/grafana/.cache/puppeteer/chrome/linux-116.0.5845.96/chrome-linux64/chrome", F_OK) = -1 ENOENT (No such file or directory)

148   mprotect(0x7f73ce903000, 245760, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
148   mprotect(0x7f73ce903000, 245760, PROT_READ|PROT_EXEC) = 0
148   mprotect(0x7f73ce903000, 245760, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
148   mprotect(0x7f73ce903000, 245760, PROT_READ|PROT_EXEC) = 0
148   write(18, "Error: Could not find Chrome (ver. 116.0.5845.96). This can occur if either\n 1. you did not perform an installation before running the script (e.g. `npm install`) or\n 2. your cache path is incorrectly configured (which is: /home/grafana/.cache/puppeteer).\n"..., 1238) = 1238
148   futex(0x342d794, FUTEX_WAKE_PRIVATE, 2147483647) = 2
```

**Environment**:
- Grafana Image Renderer version: 3.8.0
- Grafana version: 10.1.0 and 10.0.3
- Installed plugin or remote renderer service: plugin
- OS Grafana Image Renderer is installed on: Alpine/Ubuntu/Docker
- Host OS used to build Docker image: Ubuntu 22.04, with package docker.io `20.10.25-0ubuntu1~22.04.2` (which is after the [recent chown issue](https://bugs.launchpad.net/ubuntu/+source/docker.io-app/+bug/2029523))

**Comment by Hipska** [comment]
I have the same issue (saying it is compiled for another architecture) and it keeps restarting Grafana because of this. Reverting to 3.7.x resolves the issue.

I'm not running the plugin or Grafana in Docker, but plain on the system (RHEL 7).

**Comment by olafrauch** [comment]
Exactly the same here. Running it native on AWS EC2 centos 8 stream AMI based.
Downgrade to 3.7.2 was the quick workaround.

We also tested to manually install the documented yum dependencies according to https://grafana.com/docs/grafana/latest/setup-grafana/image-rendering/troubleshooting/
No difference.

**Comment by AgnesToulet** [comment]
Hello! Thank you for reporting this, we are investigating this issue and we'll keep you updated.
