### ISSUE TITLE
Can I get help with request errors?

### ISSUE THREAD

**Issue by Blue-Comet** [grafana/grafana-image-renderer#491]
Hello, I installed render-server as standalone and ran it using node.
And I started by setting localhost:8081 in grafana.ini, but the following error occurs when using Direct Linke rendered image.

Could I possibly get some help?

`logger=context userId=1 orgId=1 uname=admin t=2024-01-22T18:03:26.787530151Z level=error msg="Request error" error="Context.HTML - Error rendering template: error. You may need to build frontend assets \n template: error:16:35: executing \"error\" at <.ContentDeliveryURL>: can't evaluate field ContentDeliveryURL in type struct { Title string; AppTitle string; AppSubUrl string; Theme string; ErrorMsg error }" stack="github.com/grafana/grafana/pkg/web/context.go:112 (0x6147bc7)\ngithub.com/grafana/grafana/pkg/services/contexthandler/model/model.go:54 (0x614fe44)\ngithub.com/grafana/grafana/pkg/api/render.go:87 (0x87c5944)\ngithub.com/grafana/grafana/pkg/api/response/web_hack.go:40 (0x615608f)\nnet/http/server.go:2136 (0x538ee28)\ngithub.com/grafana/grafana/pkg/web/macaron.go:131 (0x6148b2e)\nnet/http/server.go:2136 (0x538ee28)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x6148bd2)\nnet/http/server.go:2136 (0x538ee28)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x6148bd2)\nnet/http/server.go:2136 (0x538ee28)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x6148bd2)\nnet/http/server.go:2136 (0x538ee28)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x6148bd2)\nnet/http/server.go:2136 (0x538ee28)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x6148bd2)\nnet/http/server.go:2136 (0x538ee28)\ngithub.com/grafana/grafana/pkg/services/contexthandler/contexthandler.go:145 (0x87cf79b)\nnet/http/server.go:2136 (0x538ee28)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x6148bd2)\nnet/http/server.go:2136 (0x538ee28)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x6148bd2)\nnet/http/server.go:2136 (0x538ee28)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x6148bd2)\nnet/http/server.go:2136 (0x538ee28)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x6148bd2)\nnet/http/server.go:2136 (0x538ee28)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x6148bd2)\nnet/http/server.go:2136 (0x538ee28)\ngithub.com/grafana/grafana/pkg/web/render.go:44 (0x61496bd)\nnet/http/server.go:2136 (0x538ee28)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x6148bd2)\nnet/http/server.go:2136 (0x538ee28)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x6148bd2)\nnet/http/server.go:2136 (0x538ee28)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x6148bd2)\nnet/http/server.go:2136 (0x538ee28)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x6148bd2)\nnet/http/server.go:2136 (0x538ee28)\ngithub.com/grafana/grafana/pkg/middleware/csrf/csrf.go:66 (0x7e1eb7a)\nnet/http/server.go:2136 (0x538ee28)\ngithub.com/grafana/grafana/pkg/middleware/recovery.go:179 (0x87a9f75)\nnet/http/server.go:2136 (0x538ee28)\ngithub.com/grafana/grafana/pkg/middleware/loggermw/logger.go:72 (0x7e1fb96)\nnet/http/server.go:2136 (0x538ee28)\ngithub.com/grafana/grafana/pkg/middleware/request_metrics.go:83 (0x672d735)\nnet/http/server.go:2136 (0x538ee28)\ngithub.com/grafana/grafana/pkg/middleware/request_tracing.go:88 (0x87aabd5)\nnet/http/server.go:2136 (0x538ee28)\ngithub.com/grafana/grafana/pkg/middleware/requestmeta/request_metadata.go:66 (0x87ce835)\nnet/http/server.go:2136 (0x538ee28)\ngithub.com/grafana/grafana/pkg/web/context.go:52 (0x6147616)\ngithub.com/grafana/grafana/pkg/web/router.go:155 (0x614ad6d)\ngithub.com/grafana/grafana/pkg/web/router.go:221 (0x614b8b4)\ngithub.com/grafana/grafana/pkg/web/macaron.go:163 (0x6148ffc)\nnet/http/server.go:2938 (0x5391b0d)\nnet/http/server.go:2009 (0x538d9f3)\nruntime/asm_amd64.s:1650 (0x50553e0)\n"`

Debug Messages

`{"level":"error","message":"Request failed","stack":"Error: Could not find Chrome (ver. 116.0.5845.96). This can occur if either\n 1. you did not perform an installation before running the script (e.g. `npm install`) or\n 2. your cache path is incorrectly configured (which is: /root/.cache/puppeteer).\nFor (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.\n    at ChromeLauncher.resolveExecutablePath (/opt/grafana-image-renderer/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:300:27)\n    at ChromeLauncher.executablePath (/opt/grafana-image-renderer/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:180:25)\n    at ChromeLauncher.computeLaunchArguments (/opt/grafana-image-renderer/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:97:37)\n    at async ChromeLauncher.launch (/opt/grafana-image-renderer/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:79:28)\n    at async Browser.render (/opt/grafana-image-renderer/build/browser/browser.js:226:23)\n    at async HttpServer.render (/opt/grafana-image-renderer/build/service/http-server.js:53:28)","url":"/render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=500&renderKey=UOwnSOIWFtpGzZC188tHRZ89Xtzawwit&timeout=60&timezone=Asia%2FSeoul&url=http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2Ff68f72df-a101-401c-89ef-2a7115ce9e84%2Fnew-dashboard%3ForgId%3D1%26from%3D1705925419467%26to%3D1705947019467%26panelId%3D1%26width%3D1000%26height%3D500%26tz%3DAsia%252FSeoul%26render%3D1&width=1000"}
{"level":"error","message":"::ffff:127.0.0.1 - - [22/Jan/2024:18:10:20 +0000] \"GET /render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=500&renderKey=UOwnSOIWFtpGzZC188tHRZ89Xtzawwit&timeout=60&timezone=Asia%2FSeoul&url=http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2Ff68f72df-a101-401c-89ef-2a7115ce9e84%2Fnew-dashboard%3ForgId%3D1%26from%3D1705925419467%26to%3D1705947019467%26panelId%3D1%26width%3D1000%26height%3D500%26tz%3DAsia%252FSeoul%26render%3D1&width=1000 HTTP/1.1\" 500 96 \"-\" \"Grafana/10.2.3\"\n"}`

already chrom installed
```
ubuntu@ubuntu:/var/lib/grafana/plugins/grafana-image-renderer$ sudo dpkg -l | grep chrom
ii  chromium-browser                      1:85.0.4183.83-0ubuntu2.22.04.1         amd64        Transitional package - chromium-browser -> chromium snap
```

```
ubuntu@ubuntu:/var/lib/grafana/plugins/grafana-image-renderer$ sudo cat /etc/grafana/grafana.ini |grep chrom
# See ICU’s metaZones.txt (https://cs.chromium.org/chromium/src/third_party/icu/source/data/misc/metaZones.txt) for a list of supported
# here (https://peter.sh/experiments/chromium-command-line-switches/). Multiple arguments is separated with comma-character.
rendering_chrome_bin = /usr/bin/chromium-browser
```

```
ubuntu@ubuntu:/var/lib/grafana/plugins/grafana-image-renderer$ which chromium-browser
/usr/bin/chromium-browser
```

**Comment by Blue-Comet** [comment]
The problem has been resolved, and running with root privileges is working well.!!!
