### ISSUE TITLE
image rendering times out sporadically

### ISSUE THREAD

**Issue by jluebbe** [grafana/grafana-image-renderer#582]
**What happened**:
After updating grafana (to 11.3.1) and the grafana-image-renderer (to 3.11.6), some image rendering requests fail with a timeout, while most work.
As far as I can tell it affects ~25% of requests.

The log message from the renderer is:
```
logger=plugin.grafana-image-renderer t=2024-11-20T20:22:04.460896286+01:00 level=debug msg="Render request received" url="http://127.0.0.1:3000/d-solo/zglP5XSWk/node?panelId=4&var-node=74acb92689a8&from=now-1d&width=650&height=350&theme=light&render=1"
logger=plugin.grafana-image-renderer t=2024-11-20T20:22:05.585531541+01:00 level=error msg="Browser request failed" url="http://127.0.0.1:3000/api/ds/query?ds_type=influxdb&requestId=SQR100" method=POST failure=net::ERR_ABORTED
logger=plugin.grafana-image-renderer t=2024-11-20T20:22:34.507991251+01:00 level=error msg="Error while waiting for the panels to load" url="http://127.0.0.1:3000/d-solo/zglP5XSWk/node?panelId=4&var-node=74acb92689a8&from=now-1d&width=650&height=350&theme=light&render=1" err="TargetCloseError: Protocol error (Runtime.callFunctionOn): Target closed
    at CallbackRegistry.clear (/snapshot/src/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:72:36)
    at CdpCDPSession._onClosed (/snapshot/src/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:101:25)
    at Connection.onMessage (/snapshot/src/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:130:25)
    at WebSocket.<anonymous> (/snapshot/src/node_modules/puppeteer-core/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:44:32)
    at callListener (/snapshot/src/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/snapshot/src/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:537:28)
    at Receiver.receiverOnMessage (/snapshot/src/node_modules/ws/lib/websocket.js:1220:20)
    at Receiver.emit (node:events:537:28)
    at Immediate.<anonymous> (/snapshot/src/node_modules/ws/lib/receiver.js:601:16)"
logger=plugin.grafana-image-renderer t=2024-11-20T20:22:34.508769665+01:00 level=error msg="Render request failed" url="http://127.0.0.1:3000/d-solo/zglP5XSWk/node?panelId=4&var-node=74acb92689a8&from=now-1d&width=650&height=350&theme=light&render=1" error="Error: Timeout hit: 30000"
```

The influx log doesn't show anything obviously problematic.

**What you expected to happen**:
All requests render correctly.

**How to reproduce it (as minimally and precisely as possible)**:
The images are used on public pages: https://freifunk-bs.de/map/#!/en/map/68725132e5cb

**Anything else we need to know?**:
In the error case, the renderer responds with a truncated error message instead of the image:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width" />
    <meta name="theme-color" content="#000" />

    <title>Grafana - Error</title>

    <base href="/grafana/" />

    
    <link rel="stylesheet" href="
```

**Environment**:
- Grafana Image Renderer version: 3.11.6
- Grafana version: 11.3.1
- Installed plugin or remote renderer service: installed as plugin
- OS Grafana Image Renderer is installed on: Debian 12.8
- User OS & Browser: Debian Chromium, Andorid, curl
- Others:

**Comment by mikerevellesciplay** [comment]
had the same issue with 11.3.1, spent more than a week troubleshooting this and it looks like downgrading to 11.2.4 fixed it.

**Comment by manny4566** [comment]
I can confirm the problem

**Comment by KausL** [comment]
I can confirm this issue:

- With Grafana v10 I use the rendering with a link like this

https://10.10.20.7:3000/render/d-solo/dtfndb010/10-system-performance-24h-overview/?panelId=34&width=260&height=260&from=1733237940000&to=1733324340000

The image generation takes around 5s depending on the panel.

- With Grafana 11.3.1 I use the same url is used but now the image generation takes around 30s which expands the generation of my report email from 5min to 30min which is not really critical but very strange.

After playing around with the renderer settings I found out that using the direct link button via the grafana UI this is wotking as fast as under v10. So the difference is that the link callled by the button contains all the vars defined in the dashboard (no matter if it is used in the panel or not). The Link looks like this now:

https://10.10.20.7:3000/render/d-solo/dtfndb010?orgId=1&from=2024-12-03T15:10:40.882Z&to=2024-12-04T15:10:40.882Z&var-sitea=BRE&var-siteb=HAM&var-sitec=KLN&var-maxOpsRDS=99600&var-maxOpsBDS=28800&var-maxQryBDS=17400&var-maxUpdBDS=3800&var-srvCountBDS=6&var-srvCountRDS=6&var-srvCountBDSOneSite=2&refresh=1m&panelId=panel-34&__feature.dashboardSceneSolo&width=1000&height=500&tz=Europe%2FBerlin

Can anybody explain how this issues/bug can be solved/switched back to the old behaviour?

Thanks in advance!

**Comment by mikerevellesciplay** [comment]
@evictorero @lucychen-grafana do you guys test this stuff?

**Comment by jluebbe** [comment]
> had the same issue with 11.3.1, spent more than a week troubleshooting this and it looks like downgrading to 11.2.4 fixed it.

Thanks for the hint. I've downgraded Grafana to 11.2.4 and now rendering is reliable.

**Comment by Andrew-Hinson** [comment]
I'm also dealing with this issue, I have an app that "recreates" grafana dashboards for posting to slack, notably, only panels that query snowflake are having issues, likely due to some small lag as the queries are fairly quick. Before we upgraded Grafana, no issues. Now, I routinely get blank panels sent to slack. Downgrading is not an option for us.

**Comment by manny4566** [comment]
> Hi everyone. Thanks for reporting this. We are trying to triage this issue and isolate this case to be able to reproduce it. As far as I can tell, all of you are having issues after upgrading Grafana to 11.3.1 and consuming the render API from an external app using the same link you used in older versions. We suspect this problem could be related to a retro compatibility issue.
> 
> **Can you help us answering these questions?**
> 
> * When does it start failing? e.g After upgrading to 11.3.1 from 11.2.0
> * Which image renderer version are you using?
> * Is the image renderer configured as a plugin or as an external service?
> * Which data sources use the panels that are failing?
> * Does this issue happen randomly or can you reproduce it consistently?
> * If you grab the URL from the panel UI in Grafana 11.3.1. Does it fail?
> * Does adding the query param `__feature.dashboardSceneSolo` to the old URL make it work?

Can you help us answering these questions?

When does it start failing? e.g After upgrading to 11.3.1 from 11.2.0 -> **_on of the last updates grafana-11.3.0-1.x86_64 or grafana-11.3.1-1.x86_64. Bevor 11.3.0 i had grafana-11.2.2-1.x86_64_**
Which image renderer version are you using? **_3.11.6_**
Is the image renderer configured as a plugin or as an external service? _**Plugin on the Grafana Host**_
Which data sources use the panels that are failing? _**InfluxDBv2**_
Does this issue happen randomly or can you reproduce it consistently? **_fairly regularly if not always_** 
If you grab the URL from the panel UI in Grafana 11.3.1. Does it fail? _**It run into the same timeout error**_
Does adding the query param __feature.dashboardSceneSolo to the old URL make it work? **_no. example URL:_**
http://HOST:3000/d-solo/icinga2/icinga2-with-influxdb?from=now-3h&height=480&orgId=1&panelId=3&render=1&theme=dark&timezone=browser&to=now&var-command=load&var-disk=%24__all&var-hostname=XXX&var-service=Load+1h&var-threadcount=%24__all&width=1000&__feature.dashboardSceneSolo=false

Also not without "&__feature.dashboardSceneSolo=false"


I hope this helps.
Thank you

**Comment by manny4566** [comment]
Hi,
i think i'm getting closer to the problem.

The problem is the seems to be the panal id. With 11.3.0 the variable for the panal id changed:

v11.2.2
https://XXX/d/icinga2/icinga2-with-influxdb?var-hostname=XXX&var-service=Load%201h&var-command=load&from=now-3h&to=now&orgId=1&viewPanel=3

Here it is **&viewPanel=3**


v11.3.0
https://XXX/d/icinga2/icinga2-with-influxdb?var-hostname=XXX&var-service=Load%201h&var-command=load&from=now-3h&to=now&orgId=1&viewPanel=panel-3&timezone=browser&var-disk=$__all&var-threadcount=$__all

Here it is **&viewPanel=panel-3**.

Futhermore automatically "&timezone=browser&var-disk=$__all&var-threadcount=$__all" is added for variable without a definition ($__all).
In 11.2.2 they are not added automatically to the URL


##################
As you can see, it is an Icinga2 implementation. The url is build by Icinga2, concretely the Icinga2 grafana plugin. I think there is a discrepancy between the Icinga2 module and the Grafana panal id variable, which has changed in 11.3.0. 
Possibly also in interaction with the image renderer plugin.
I use this environment:

Icinga2 2.14.3
Grafana Plugin v2.0.3 - https://github.com/Mikesch-mp/icingaweb2-module-grafana
same Problem with v3.0.0 - https://github.com/NETWAYS/icingaweb2-module-grafana 

Grafana 11.3.2 ( But also with v11.3.0 ). With v11.2.2 it works.
grafana-image-renderer  v3.11.6

I hope this will help.
I will also add this comment to other Github tickets.

**Comment by Pedritod** [comment]
We are also facing this issue, by doing the downgrade it works again. Thank you for the nice explanation and investigation of the bug

**Comment by okossuth** [comment]
Same here, i did some tests and there were issues rendering some panels using grafana 11.4.0 and grafana-image-renderer 3.11.6 running as external service. Once i downgraded grafana to 11.2.5, rendering panels worked 100% of the time.

**Comment by herbetom** [comment]
For us the perceived "timeout problem" appears to have turned out to be a missing Variable that was used in the title of the dashboard.

---

I'm speculating that there previously was some form of redirect or url rewrite taking place which poulated that var (as the rendered image contained it's content before), but that doesn't seem to work anymore.


So everyone who is having issues might want to check that **all variables** which are needed are provided. It doesn't seem to fail gracefully if not all are present.

---

Just as a tip, if it's not consitently broken it might of course be something else.

**Comment by Pedritod** [comment]
We thought that missing variables might be the root cause as well, especially since they were used in the dashboard title and sometimes they were not filled. However, after testing over several days, we observed inconsistent behavior — sometimes it worked, and other times it didn’t.

**Comment by zvarnes** [comment]
Downgraded grafana to v11.2.4 and the renderer is working again as expected.

**Comment by pgassmann** [comment]
I am also debugging this issue.
I cannot yet pinpoint what exactly makes it break, sometimes it works on the same panels, and sometimes it doesn't. 
Feels like some race condition.
I tested it using the share link > Generate image feature of the panel:
It happens more often on some panels/dashboards than on others. on some dashboard I cannot reproduce the issue, the images are always rendered.

**Comment by Suraxius** [comment]
Tested. Same result.

**Comment by vincent-olivert-riera** [comment]
We also had to downgrade from 11.5 to 11.2 because of this bug.

**Comment by Azzonith** [comment]
Hey everyone, 

As a temporary solution, while bug is being fixed, you could query all the dashboard variables and append them to a panel render link.

resp = requests.get(f"{grafana_url}/api/dashboards/uid/{dashboard_uid}", headers=headers)
dashboard_json = resp.json()
variables = [var['name'] for var in dashboard_json['dashboard'].get('templating', {}).get('list', [])]

variables_payload = ''
    for var_name in variables:
        variables_payload += f"&var-{var_name}=All"

Final panel render link would look like this:
render_url = f'{grafana_url}/render/d-solo/{dashboard_uid}/{dashboard_slug}{variables_payload}'

**Comment by vincent-olivert-riera** [comment]
> As a temporary solution, while bug is being fixed, you could query all the dashboard variables and append them to a panel render link.
> [...]
> variables_payload = '' for var_name in variables: variables_payload += f"&var-{var_name}=All"

Uhm..., I think this cannot be considered a solution because you are setting the value `All` to all variables. The rendered panel may not be what you expect, because for some missing variables their default value (which is used as a fallback when you don't provide the variable in the URL) may be different than `All`.

Moreover, your solution is setting `All` to all variables regardless, even if some of them were already included in the URL. That means you would be overriding the value set by the user.

**Comment by vincent-olivert-riera** [comment]
Tested with the latest releases from today (11.5.3 and 11.6.0) and the problem is still there.

**Comment by maxervo** [comment]
Also seeing the same issue on Grafana 11.3.2. The time-out always happen in our case, even when first creating a new dashboard without any variables then creating a dummy panel like below. Clicking on `Share` > `Direct link rendered image` for that dummy panel opens a new tab that tries to load something for some time then displays a blank webpage:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width" />
    <meta name="theme-color" content="#000" />

    <title>Grafana - Error</title>

    <base href="/" />

    
    <link rel="stylesheet" href="
```
Clicking `Direct link rendered image` opens up this URL (and no variables for this dashboard):
```
https://grafana.somedomain.io/d/fehtvplxgodtsd/screenshot-test?from=1743691953987&to=1743713553987&orgId=1&viewPanel=1
```

<img width="1439" alt="Image" src="https://github.com/user-attachments/assets/7c104cc9-e957-4376-9c00-5ef517b4f10f" />

**Comment by denisse-dev** [comment]
I'm also seeing this issue with Grafana 11.6.1.

**Comment by manny4566** [comment]
> Hey everyone,
> 
> As a temporary solution, while bug is being fixed, you could query all the dashboard variables and append them to a panel render link.
> 
> resp = requests.get(f"{grafana_url}/api/dashboards/uid/{dashboard_uid}", headers=headers) dashboard_json = resp.json() variables = [var['name'] for var in dashboard_json['dashboard'].get('templating', {}).get('list', [])]
> 
> variables_payload = '' for var_name in variables: variables_payload += f"&var-{var_name}=All"
> 
> Final panel render link would look like this: render_url = f'{grafana_url}/render/d-solo/{dashboard_uid}/{dashboard_slug}{variables_payload}'

I can confirm that it works with a workaroud if you query all variables to the generated render link. So it is definitely a problem with the creation on the render link and if this link has variables.

**Comment by maurerle** [comment]
The problem occurs when the dashboard has multiple variables, but the rendering URL does not include all variables.
This is still the case for Grafana v12.1.0

The best solution is to leave the missing variables empty and append them: `&var-nodetolink=&var-hostname=`

For example this does time out:
`https://example.com/render/d-solo/000000002/node?panelId=1&var-node=requiredName`

While this works:
`https://example.com/render/d-solo/000000002/node?panelId=1&var-node=requiredName&var-nodetolink=&var-hostname=`

I really hope, this gets fixed some day..

**Comment by manny4566** [comment]
> The problem occurs when the dashboard has multiple variables, but the rendering URL does not include all variables. This is still the case for Grafana v12.1.0
> 
> The best solution is to leave the missing variables empty and append them: `&var-nodetolink=&var-hostname=`
> 
> For example this does time out: `https://example.com/render/d-solo/000000002/node?panelId=1&var-node=requiredName`
> 
> While this works: `https://example.com/render/d-solo/000000002/node?panelId=1&var-node=requiredName&var-nodetolink=&var-hostname=`
> 
> I really hope, this gets fixed some day..

I can confirm your workaround. It also works better for me when I insert all variables as empty in the URL.
However, this sometimes results also in a timeout. So it's better, but not a fully functional workaround. But maybe that's just in my environment.

Before this error occurred, rendering the URL was not a problem, even if several variables were defined in the dashboard. This is precisely where the core problem lies.

**Comment by jellyfinuser** [comment]
I think i have same issue, latest grafana docker image and latest render docker image. Sometimes works and another no, but when work not appear all boxes in PDF, only one. My dashboards has two variables that are used to create boxes in Dashboard for every variable value, repeating for each. I have spend a lot of hours trying to solve this without success. What option recomend me to make this work? Download grafana version?

**Comment by zvarnes** [comment]
I've been following this thread for 10 months now hoping for a solution. Does anyone actually know the root cause, or know if it's being worked on? @evictorero Early in the thread you mentioned the team was working on determining the cause, but I see nobody is assigned to this issue currently. Are you able to provide any insight? I'm happy to provide any logs/configs to help track it down if that's helpful. Thanks in advance!

**Comment by macabu** [comment]
Hi folks, I've been trying to reproduce the issue but without success, the rendering works every time. I know this is not working for you, so there must be something I am missing, and so I am looking for help.

@vincent-olivert-riera could you have a look and see if you can spot something? I'd appreciate it 🙂 

Here's my setup and instructions, I am running with Docker Compose:
```yaml
services:
  renderer:
    image: grafana/grafana-image-renderer:3.11.6
    ports:
      - "8081:8081"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.3.1
    ports:
      - "3000:3000"
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
```

Here's the dashboard I created:

<img width="969" height="453" alt="Image" src="https://github.com/user-attachments/assets/add92a27-f3dc-4baf-80c5-14be0c881970" />

<img width="1439" height="362" alt="Image" src="https://github.com/user-attachments/assets/83b68c12-8425-466f-a36e-0f06a1b0a736" />

<details>
<summary>Exported Dashboard JSON here</summary>
  
  
```json
{
  "__inputs": [
    {
      "name": "DS_PROMETHEUS",
      "label": "prometheus",
      "description": "",
      "type": "datasource",
      "pluginId": "prometheus",
      "pluginName": "Prometheus"
    }
  ],
  "__elements": {},
  "__requires": [
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "11.3.1"
    },
    {
      "type": "datasource",
      "id": "prometheus",
      "name": "Prometheus",
      "version": "1.0.0"
    },
    {
      "type": "panel",
      "id": "timeseries",
      "name": "Time series",
      "version": ""
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": null,
  "links": [],
  "panels": [
    {
      "datasource": {
        "type": "prometheus",
        "uid": "${dSrcVar}"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisBorderShow": false,
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "barWidthFactor": 0.6,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "insertNulls": false,
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 1,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "pluginVersion": "11.3.1",
      "targets": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "${DS_PROMETHEUS}"
          },
          "editorMode": "code",
          "expr": "rate(process_cpu_seconds_total{app=\"${qApp}\", job=\"${custom1}\"}[$__rate_interval])",
          "legendFormat": "__auto",
          "range": true,
          "refId": "A"
        }
      ],
      "title": "CPU Usage - ${custom1}",
      "type": "timeseries"
    }
  ],
  "schemaVersion": 40,
  "tags": [],
  "templating": {
    "list": [
      {
        "current": {},
        "definition": "label_values(process_max_fds,app)",
        "includeAll": false,
        "name": "qApp",
        "options": [],
        "query": {
          "qryType": 1,
          "query": "label_values(process_max_fds,app)",
          "refId": "PrometheusVariableQueryEditor-VariableQuery"
        },
        "refresh": 1,
        "regex": "",
        "type": "query"
      },
      {
        "current": {
          "text": "prometheus",
          "value": "prometheus"
        },
        "includeAll": false,
        "name": "custom1",
        "options": [
          {
            "selected": true,
            "text": "prometheus",
            "value": "prometheus"
          }
        ],
        "query": "prometheus",
        "type": "custom"
      },
      {
        "current": {},
        "includeAll": false,
        "name": "dSrcVar",
        "options": [],
        "query": "prometheus",
        "refresh": 1,
        "regex": "",
        "type": "datasource"
      }
    ]
  },
  "time": {
    "from": "now-15m",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "browser",
  "title": "New dashboard",
  "uid": "afak7zg8hqby8f",
  "version": 2,
  "weekStart": ""
}
```
</details>

Using the following variables: "query", "custom", "datasource":
<img width="398" height="200" alt="Image" src="https://github.com/user-attachments/assets/93c919c0-577f-4d7a-a88f-76cacc6bac44" />

<details>
<summary>Page details for each variable</summary>

<img width="594" height="871" alt="Image" src="https://github.com/user-attachments/assets/2a4e5ced-f819-4f8d-aa67-0ebddbfa26d5" />

<img width="618" height="926" alt="Image" src="https://github.com/user-attachments/assets/4fbdc191-1b6a-41c9-9e27-d76531d6b758" />

<img width="596" height="676" alt="Image" src="https://github.com/user-attachments/assets/fa2b0be2-2c11-4ee5-9351-b853994773fb" />
</details>

If I click on the panel, then Share, then "Direct link rendered image", I get this URL:
```
http://localhost:3000/render/d-solo/afak7zg8hqby8f?orgId=1&from=2026-01-18T17:16:16.092Z&to=2026-01-18T17:31:16.092Z&timezone=browser&var-query0=&var-qApp=prometheus&var-query0-2=&var-custom1=prometheus&var-query0-3=&var-dataSrc=&var-dSrcVar=ffak7pugy7sw0f&panelId=panel-1&__feature.dashboardSceneSolo&width=1000&height=500&tz=Europe%2FMadrid
```

If I remove all variables, it still works:
```
http://localhost:3000/render/d-solo/afak7zg8hqby8f?orgId=1&from=2026-01-18T17:16:16.092Z&to=2026-01-18T17:31:16.092Z&timezone=browser&panelId=panel-1&__feature.dashboardSceneSolo&width=1000&height=500&tz=Europe%2FMadrid
```

I also tried to remove almost all query params similar to what @maurerle had, and that also still works:
```
http://localhost:3000/render/d-solo/afak7zg8hqby8f/new-dashboard?panelId=1&from=now-1d&width=650&height=350&theme=light
```

Here's a demo:

https://github.com/user-attachments/assets/4e03336c-c9cc-4651-9581-5a7d84fb486c

**Comment by zvarnes** [comment]
@macabu Your instance looks a bit different from mine for some reason, but my "copy image link" appears to be working. It's the "generate image" which appears to be broken. It use to generate and show the image here, but instead an error is shown.

<img width="632" height="766" alt="Image" src="https://github.com/user-attachments/assets/f36dfe83-e6ed-4df0-8d40-afcf0a31090e" />

I'm not sure but I believe this is the image used when configuring and sending alerts from Grafana. Not getting generated > not showing in alerts

**Comment by macabu** [comment]
@zvarnes I was using an older version of Grafana from the initial report, but tried this on the latest, and "Generate image" works.

Simple setup:
```yaml
services:
  renderer:
    image: grafana/grafana-image-renderer:v5.4.0
    ports:
      - "8081:8081"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:12.3.1
    ports:
      - "3000:3000"
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
```

https://github.com/user-attachments/assets/02f6a1ce-9575-4b00-b9c4-1e459820bd56

I am wondering if this is some config that could be affecting this. I'd like to ask you for a few things if possible:
- Have you tried with the Image Renderer and Grafana versions above? What versions are you using?
- What does your Grafana config look like?
- Can you share the dashboard you're having the issue with me, or if you can reproduce it with a simpler dashboard that you can share that would also be great.

The "Generate image" creates a request like this:
```
time=2026-01-27T14:53:15.449Z level=INFO source=/src/pkg/api/middleware/logger.go:15 msg="request complete" method=GET mux_pattern="" uri="/render?deviceScaleFactor=1.000000&domain=grafana&encoding=png&height=500&renderKey=<redacted>&timeout=60&timezone=Europe%2FMadrid&url=http%3A%2F%2Fgrafana%3A3000%2Fd-solo%2Fad79qks%3ForgId%3D1%26from%3D2026-01-27T14%3A36%3A06.817Z%26to%3D2026-01-27T14%3A51%3A06.817Z%26timezone%3Dbrowser%26var-query0%3Dprometheus%26var-query1%3Dfoo%26editIndex%3D1%26panelId%3Dpanel-1%26__feature.dashboardSceneSolo%3Dtrue%26width%3D1000%26height%3D500%26scale%3D1%26tz%3DEurope%252FMadrid%26render%3D1&width=1000" status=200 status_text=OK duration=5.043331152s
```

If I decode the `url` query param:
```
http://grafana:3000/d-solo/ad79qks?orgId=1&from=2026-01-27T14:36:06.817Z&to=2026-01-27T14:51:06.817Z&timezone=browser&var-query0=prometheus&var-query1=foo&editIndex=1&panelId=panel-1&__feature.dashboardSceneSolo=true&width=1000&height=500&scale=1&tz=Europe%2FMadrid&render=1&width=1000
```

As you can see, it is adding the variables properly. Even if it doesn't, for example, if I copy that URL with the `/d-solo/...` and remove the `var-query0`, when I go to the URL, it adds it back again.

**Comment by zvarnes** [comment]
@macabu I was able to fix the image generation issue. So the button works now. My problem was specifically the url callback being wrong. 

But even with this working, the documentation for alerts says Discord and Telegram alerts support imbedded images. I use to receive images a year ago, and now it happens sporadically. 

Here is the last time it worked, you can see it didn't send for the first alert, but did for the second. And hasn't worked since. 

![image](https://github.com/user-attachments/assets/539a155b-091c-4fd5-a068-5c564cb4ef7e)

I'll try to find some time to dive more into this again, but I haven't made any changes since this stopped working.

**Comment by macabu** [comment]
@zvarnes Have you tweaked this configuration?
```ini
[unified_alerting.screenshots]
# Enable screenshots in notifications. You must have either installed the Grafana image rendering
# plugin, or set up Grafana to use a remote rendering service.
# For more information on configuration options, refer to [rendering].
capture = false

# The timeout for capturing screenshots. If a screenshot cannot be captured within the timeout then
# the notification is sent without a screenshot. The maximum duration is 30 seconds. This timeout
# should be less than the minimum Interval of all Evaluation Groups to avoid back pressure on alert
# rule evaluation.
capture_timeout = 10s

# The maximum number of screenshots that can be taken at the same time. This option is different from
# concurrent_render_request_limit as max_concurrent_screenshots sets the number of concurrent screenshots
# that can be taken at the same time for all firing alerts where as concurrent_render_request_limit sets
# the total number of concurrent screenshots across all Grafana services.
max_concurrent_screenshots = 5
```

Try setting `capture_timeout` to something high like 30s, for example.

**Comment by macabu** [comment]
In any case, you should be seeing errors pop up in your Grafana instance if the screenshots are failing to generate

**Comment by zvarnes** [comment]
@macabu I was going down this rabbit hole last night. Even after maxing the timeout and setting concurrency to '1', it's still not completing


grafana-renderer      | 2026-01-27T15:54:55.026071139Z time=2026-01-27T15:54:55.025Z level=INFO source=/src/pkg/api/middleware/logger.go:15 msg="request complete" method=GET mux_pattern="" uri="/render?deviceScaleFactor=1.000000&domain=grafana&encoding=png&height=500&renderKey=Z6MYFCMl4MZOENSkmySEcivOwxB3mSTK&timeout=30&timezone=&url=http%3A%2F%2Fgrafana%3A3000%2Fd-solo%2FxfpJB9FGz%2Fnode-exporter-for-prometheus-dashboard-en-20201010%3ForgId%3D1%26panelId%3D174%26render%3D1&width=1000" status=408 status_text="Request Timeout" duration=30.007393809s

**Comment by macabu** [comment]
It could also be that Chromium is too not getting enough resources to process the request. Check whether the Image Renderer is getting CPU throttled or memory bottlenecks.

For example, we deploy on Kubernetes and give it 3 CPU / 8 Gi of memory per pod.

At least that what it looks like, given it is not consistently failing (also I suppose relates to the original report).

In any case if you can share this node exporter dashboard and how you are setting up the alert rule, I can give it a try and share my findings.

**Comment by KausL** [comment]
I have possibly found the mechanism which may be the root cause of the probelm.
In the Dashboard from where I query some panels I have defined some vars. 

Some of them are simple SELECT queries like:

`SELECT SUM(mo) FROM (SELECT (LAST(maxOps)*serverCount) AS mo FROM "ratecontrol" WHERE type='R' AND time > now()-24h GROUP BY xda)`

--> If I remove these wars from the query link, the processing time is not affected.

But then I have 3 vars with the SHOW cmd for getting explicite site values instead of a list of all sites:

`sitea = SHOW TAG VALUES WITH KEY = "site" LIMIT 1`
`siteb = SHOW TAG VALUES WITH KEY = "site" LIMIT 1 OFFSET 1`
`sitec = SHOW TAG VALUES WITH KEY = "site" LIMIT 1 OFFSET 2`

--> If I remove one (or all) of these 3 vars, then the processing time increases significantly.

WA:
Adding these vars w/o values `...&var-sitea=&var-siteb=&var-sitec=&...` will solve the issue (but is not really nice as it migth happen, that I need to set/use these vars in my tool...).

Fun fact:
The var with the simple query w/o LIMIT/OFFSET did not increase the processing time, if the var is deleted from the query link!
`sites = SHOW TAG VALUES WITH KEY = "site"`

Hopefully this will help to identify the root cause and solve it. 
Perhaps somebody may confirm this finding.

Thanks in advance!

**Comment by zvarnes** [comment]
I have more than 8gb of ram available, and it's still intermittent...

<img width="993" height="306" alt="Image" src="https://github.com/user-attachments/assets/60f09840-13fe-4564-af2b-03897340e63e" />

**Comment by macabu** [comment]
Thanks all. We've made some fixes in Grafana to properly propagate query variables and our internal monitoring shows promising results in the stability of panel screenshots!

For on-prem, it should be released in the following versions: 13.0.0, 12.4.3, 12.3.7, 12.2.9 and 11.6.15

Give it a try when these release, paired with a recent version of the Image Renderer, and let us know in case you still have issues.
