### ISSUE TITLE
Docker variant: WegGL error for rendering panel based on Geomap plugin

### ISSUE THREAD

**Issue by RastaTaz** [grafana/grafana-image-renderer#585]
**What happened**:
I want to perform PNG export of a panel that is basad on Geomap plugin `vaduga-mapgl-panel`.
I did only get legends of the map/panel in the resulting PNG.
Further look into renderer container logs shows error in below log extract (censored URL to protect privacy):
```
2024-12-08T15:44:46.413033802Z ERR Browser console error | column=1363281 line=1 msg=deck: Failed to create WebGL context: Failed to create a WebGL2 context.  url=http://grafana:3000/public/plugins/vaduga-mapgl-panel/module.js?_cache=1.6.1 
2024-12-08T15:44:46.416867379Z ERR Browser uncaught exception | error=Error: Failed to create WebGL context: Failed to create a WebGL2 context.
i (http://grafana:3000/public/plugins/vaduga-mapgl-panel/module.js?_cache=1.6.1:2:1336527)
new fg (http://grafana:3000/public/plugins/vaduga-mapgl-panel/module.js?_cache=1.6.1:2:1336809)
fg.create (http://grafana:3000/public/plugins/vaduga-mapgl-panel/module.js?_cache=1.6.1:2:1335786) 
2024-12-08T15:45:44.451310624Z ERR Error while trying to prepare page for screenshot | err=TimeoutError: Navigation timeout of 60000 ms exceeded
    at new Deferred (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/Deferred.js:59:34)
    at Deferred.create (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/Deferred.js:21:16)
    at new LifecycleWatcher (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/LifecycleWatcher.js:69:60)
    at CdpFrame.goto (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Frame.js:151:29)
    at CdpFrame.<anonymous> (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/decorators.js:98:27)
    at CdpPage.goto (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:588:43)
    at /usr/src/app/build/browser/browser.js:290:29
    at Browser.withTimingMetrics (/usr/src/app/build/browser/browser.js:443:20)
    at Browser.takeScreenshot (/usr/src/app/build/browser/browser.js:286:24)
    at async Browser.render (/usr/src/app/build/browser/browser.js:260:20) url=http://grafana:3000/d-solo/<CENSORED_DASHBOARD-ID>/<CENSORED_DASHBOARD-NAME>?orgId=2&from=now-5m&to=now&panelId=11&width=960&height=540&render=1 
```

**What you expected to happen**:
Obtain PNG that includes background tiles of map

**How to reproduce it (as minimally and precisely as possible)**:
- Use grafana and render plugin in docker container as documented
- add a panel using the `vaduga-mapgl-panel` geomap
- perfrom call to render plugin to render panel

**Anything else we need to know?**:
Current setup I'm using works perfectly well when requesting render on other panels (standard graphs panels).

**Environment**:
- Grafana Image Renderer version: current latest version of grafana/grafana-image-renderer image on dockerhub (= v3.11.6 according to tag)
- Grafana version: current latest version of grafana/grafana-enterprise (= v11.4.0 according to tag)
- Installed plugin or remote renderer service: remote renderer through docker image
- OS Grafana Image Renderer is installed on: CentOS Stream 9, but again it's using docker so OS shouln't be relevant
- User OS & Browser: Ubuntu 24.04 and Brave Browser (but not relevant to current issue either)
- Others: none that I can think of being relevant to issue, but just ask and I will provide answers...

**Comment by RastaTaz** [comment]
Agnes,

This new commit cured a more recent bug that I had with the "geomap" plugin I was using insted of "vadua-mapgl-panel".

Indeed,I had same issues with below erros in the logs of the container since last update using the "latest" container tag:
```
ERR Browser uncaught exception | error=TypeError: Cannot read properties of undefined (reading 'keys') 
ERR Browser uncaught exception | error=TypeError: Cannot read properties of null (reading 'createTexture') 
```
=> Despite I used the container with tag "master-497f9cb" (instead of the one corresponding to your commit, the "master-0ab2684", but as it was newer than yours I supposed it would also contain it): not sure this the commit that corrects my recent issue, but I now have my screenshots back !

Anyways, thanks a lot !
