### ISSUE TITLE
remote rendering: Request failed "500 Internal Server Error"

### ISSUE THREAD

**Issue by flynn1973** [grafana/grafana-image-renderer#99]
**What happened**:
Clicking on the "Direct Link rendered Image" button produces the following errror.

grafana.log
````
t=2020-02-11T12:06:59+0100 lvl=eror msg="Remote rendering request failed" logger=rendering error="500 Internal Server Error"
t=2020-02-11T12:06:59+0100 lvl=eror msg="Rendering failed." logger=context userId=15 orgId=1 uname=tremch error="Remote rendering request failed. 500: 500 Internal Server Error"
````

renderer output
````
{"level":"info","message":"HTTP Server started, listening at http://localhost:8081"}
{"url":"/render?domain=172.16.88.85&encoding=&height=500&renderKey=Z8ZLYrDRB9YTRQ10s62PSyMkGDuGiYJg&timeout=60&timezone=Europe%2FVienna&url=http%3A%2F%2F172.16.88.85%3A3000%2Fd-solo%2FBLqQ4cyZz%2Faix-dashboard%3ForgId%3D1%26refresh%3D5m%26from%3D1581375987540%26to%3D1581419187541%26var-ManagedSystem%3DGBG01%26var-Partition%3DAll%26var-HOST%3Dmvbmigta2-appl%26panelId%3D54%26width%3D1000%26height%3D500%26tz%3DEurope%252FVienna%26render%3D1&width=1000","stack":"TimeoutError: Navigation timeout of 30000 ms exceeded\n    at /root/go/dev/src/github.com/grafana/grafana-image-renderer/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21\n    at async FrameManager.navigateFrame (/root/go/dev/src/github.com/grafana/grafana-image-renderer/node_modules/puppeteer/lib/FrameManager.js:94:17)\n    at async Frame.goto (/root/go/dev/src/github.com/grafana/grafana-image-renderer/node_modules/puppeteer/lib/FrameManager.js:406:12)\n    at async Page.goto (/root/go/dev/src/github.com/grafana/grafana-image-renderer/node_modules/puppeteer/lib/Page.js:675:12)\n  -- ASYNC --\n    at Frame.<anonymous> (/root/go/dev/src/github.com/grafana/grafana-image-renderer/node_modules/puppeteer/lib/helper.js:111:15)\n    at Page.goto (/root/go/dev/src/github.com/grafana/grafana-image-renderer/node_modules/puppeteer/lib/Page.js:675:49)\n    at Page.<anonymous> (/root/go/dev/src/github.com/grafana/grafana-image-renderer/node_modules/puppeteer/lib/helper.js:112:23)\n    at Browser.<anonymous> (/root/go/dev/src/github.com/grafana/grafana-image-renderer/build/browser/browser.js:154:28)\n    at Generator.next (<anonymous>)\n    at /root/go/dev/src/github.com/grafana/grafana-image-renderer/build/browser/browser.js:7:71\n    at new Promise (<anonymous>)\n    at __awaiter (/root/go/dev/src/github.com/grafana/grafana-image-renderer/build/browser/browser.js:3:12)\n    at /root/go/dev/src/github.com/grafana/grafana-image-renderer/build/browser/browser.js:152:47\n    at NoOpBrowserTiming.<anonymous> (/root/go/dev/src/github.com/grafana/grafana-image-renderer/build/browser/browser.js:27:26)\n  -- ASYNC --\n    at Page.<anonymous> (/root/go/dev/src/github.com/grafana/grafana-image-renderer/node_modules/puppeteer/lib/helper.js:111:15)\n    at Browser.<anonymous> (/root/go/dev/src/github.com/grafana/grafana-image-renderer/build/browser/browser.js:154:28)\n    at Generator.next (<anonymous>)\n    at /root/go/dev/src/github.com/grafana/grafana-image-renderer/build/browser/browser.js:7:71\n    at new Promise (<anonymous>)\n    at __awaiter (/root/go/dev/src/github.com/grafana/grafana-image-renderer/build/browser/browser.js:3:12)\n    at /root/go/dev/src/github.com/grafana/grafana-image-renderer/build/browser/browser.js:152:47\n    at NoOpBrowserTiming.<anonymous> (/root/go/dev/src/github.com/grafana/grafana-image-renderer/build/browser/browser.js:27:26)\n    at Generator.next (<anonymous>)\n    at /root/go/dev/src/github.com/grafana/grafana-image-renderer/build/browser/browser.js:7:71","level":"error","message":"Request failed"}
{"message":"::1 - - [11/Feb/2020:11:06:59 +0000] \"GET /render?domain=172.16.88.85&encoding=&height=500&renderKey=Z8ZLYrDRB9YTRQ10s62PSyMkGDuGiYJg&timeout=60&timezone=Europe%2FVienna&url=http%3A%2F%2F172.16.88.85%3A3000%2Fd-solo%2FBLqQ4cyZz%2Faix-dashboard%3ForgId%3D1%26refresh%3D5m%26from%3D1581375987540%26to%3D1581419187541%26var-ManagedSystem%3DGBG01%26var-Partition%3DAll%26var-HOST%3Dmvbmigta2-appl%26panelId%3D54%26width%3D1000%26height%3D500%26tz%3DEurope%252FVienna%26render%3D1&width=1000 HTTP/1.1\" 500 96 \"-\" \"Go-http-client/1.1\"\n","level":"error"}

````

**What you expected to happen**:
image gets rendered

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
both grafana and renderer running on localhost.
renderer as standalone app
````
root@lpgaixmgmtlx01:/root/go/dev/src/github.com/grafana/grafana-image-renderer>node build/app.js server --port=8081
{"level":"info","message":"HTTP Server started, listening at http://localhost:8081"}
````

**Environment**:
- Grafana Image Renderer version: 1.0.9
- Grafana version: 6.5
- Installed plugin or remote renderer service: remote
- OS Grafana Image Renderer is installed on: Linux
- User OS & Browser: Windows/Firefox
- Others:

**Comment by flynn1973** [comment]
adding callback url to grafana config made the rendering work...strange. the docs seem to be somewhat funky.

**Comment by janwillemCA** [comment]
> adding callback url to grafana config made the rendering work...strange. the docs seem to be somewhat funky.

Which grafana config?

**Comment by antoine-42** [comment]
@janwillemCA He's talking about `/etc/grafana/grafana.ini`.

**Comment by careyer** [comment]
I am experiencing he exact same problem ... what callback address did you set? I have set mine to http://<grafana_IP>:<Grafana_Port> but it does not work anyway....
Your help is much appreciated
